config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'sites#index'

  resources :sites do 
    resources :trip_records
  end

  resources :employees do
    member do
      get 'mark_attendance'
    end
  end
  resources :attendances, only: [:index]
  

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base

  belongs_to :employee

  enum status: { Present: 'Present', Absent: 'Absent'}

  validates_presence_of :date, :status
  validates :status, inclusion: { in: statuses.keys }

end

app/models/employee.rb
class Employee < ActiveRecord::Base

  has_many :attendances

  validates_presence_of :name, :license_number, :adhaar_number, :mobile_number, :salary, :designation

  validates :adhaar_number, length: { is: 12 }
  validates :mobile_number, length: { is: 10 }
  
end

app/models/employee_payment_record.rb
class EmployeePaymentRecord < ActiveRecord::Base
  belongs_to :employee
end

app/models/site.rb
class Site < ActiveRecord::Base
  has_many :trip_records

  validates_presence_of :name, :default_truck_capacity, :lnt_basic_charge, :lnt_leading_charge, :excavation_charges
end

app/models/trip_record.rb
class TripRecord < ActiveRecord::Base

  # attr_accessor :site_id
  belongs_to :site

  #callback
  before_save :set_and_calculate_revenue

  private

  def set_and_calculate_revenue
    site = Site.find(self.site_id)
    if self.excavation_done && self.loading_and_trasportaion_done
      self.revenue = (((self.distance-1) * site.lnt_leading_charge.to_i) + site.lnt_basic_charge + site.excavation_charges ) * self.truck_capacity * self.trip_count
    end
    if self.excavation_done == true && self.loading_and_trasportaion_done == false
        self.revenue = site.excavation_charges * self.truck_capacity * self.trip_count
    end
    if self.excavation_done == false && self.loading_and_trasportaion_done == true
        self.revenue = (((self.distance-1) * site.lnt_leading_charge.to_i) + site.lnt_basic_charge) *  self.truck_capacity * self.trip_count
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validates_presence_of :email, :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  
  def index
     @employees = Employee.all
  end
  
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  include AttendancesHelper
  before_action :find_employee, only:[:edit, :update, :destroy, :show, :mark_attendance]

  def mark_attendance
    @attendance_record = check_employee_attendance_for_today(@employee)
    if @attendance_record != nil
      @attendance_record.update(status: params[:status])
    else
      @employee.attendances.create!(date: Date.current, status: params[:status])
    end
  end
  
  def index
     @employees = Employee.all
  end

  def new
     @employee = Employee.new
  end

  def create
  @employee = Employee.create(employee_params)  
    if @employee.save
      flash[:notice] = "Employee sucessfully created" 
      redirect_to employees_path  
    else
      render :new
    end   
  end

  def show
  end
  
  def edit
  end

  def update
    if @employee.update(employee_params)
      flash[:notice] = "Employee Successfully Updated"
      redirect_to employees_path
    else
      render :edit
    end
  end

  def destroy
    @employee.destroy
    flash[:alert] = "Employee Deleted Successfully "
    redirect_to employees_path
  end

  private

    def find_employee
      @employee = Employee.find(params[:id])
    end
   
    def employee_params
      params.require(:employee).permit(:name, :license_number, :adhaar_number,:mobile_number, :salary, :designation, :is_working) 
    end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

  before_action :find_site, only:[:edit, :update, :destroy]
  
  def index
     @sites = Site.all
  end

  def new
     @site = Site.new
  end

  def create
  @site = Site.create(site_params)  
    if @site.save
      flash[:notice] = "Site sucessfully created" 
      redirect_to sites_path    
    else
      render :new
    end   
  end
  
  def edit
  end

  def update
    if @site.update(site_params)
      flash[:notice] = " Site Successfully Updated"
      redirect_to sites_path
    else
      render :edit
    end
  end

  def destroy
    @site.destroy
    flash[:alert] = "Site Deleted Successfully "
    redirect_to sites_path
  end

  private

    def find_site
      @site = Site.find(params[:id])
    end
   
    def site_params
      params.require(:site).permit(:name, :default_truck_capacity,:lnt_basic_charge,:lnt_leading_charge, :excavation_charges) 
    end
end
    

app/controllers/trip_records_controller.rb
class TripRecordsController < ApplicationController
  before_action :find_trip_record, only:[:edit, :update, :destroy]
  
  def index
    if params[:site_id]
      @site = Site.find(params[:site_id])
      @trip_records = @site.trip_records.all
    else
      @trip_records = TripRecord.all
    end
  end

  def new
    @site = Site.find(params[:site_id])
    @trip_record = TripRecord.new
  end

  def create 
    @trip_record = TripRecord.create(trip_record_params) 
    if @trip_record.save
      flash[:notice] = "Trip Record sucessfully created" 
      redirect_to site_trip_records_path(params[:site_id])   
    else
      render :new
    end   
  end
  
  def edit
    @site = Site.find(params[:site_id])
  end

  def update
    if @trip_record.update(trip_record_params)
      flash[:notice] = " Trip Record Successfully Updated"
      redirect_to site_trip_records_path(params[:site_id])
    else
      render :edit
    end
  end

  def destroy
    @trip_record.destroy
    flash[:alert] = "Trip Record Deleted Successfully "
    redirect_to site_trip_records_path(params[:site_id])
  end

  private

    def find_trip_record
      @trip_record = TripRecord.find(params[:id])
    end
   
    def trip_record_params
      params.require(:trip_record).permit(:trip_date, :trip_count, :distance, :revenue, :truck_capacity, :diesel_price, :diesel_quatity, :chainage, :site_id, :excavation_done, :loading_and_trasportaion_done) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  def check_employee_attendance_for_today(employee)
    employee.attendances.where(date: Date.current).first
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/trip_records_helper.rb
module TripRecordsHelper

  def calculate_revenue
    # binding.pry
  end

  def calculate_diesel_price(diesel_quatity, diesel_price)
    diesel_quatity * diesel_price
  end

  def calculate_amount_left(revenue, diesel_price)
    revenue - diesel_price
  end

end

app/views/attendances/_employee_details.html.erb
<td><%= link_to employee.name.titleize, employee_path(employee) %></td>
<% if check_employee_attendance_for_today(employee) %>
  <td><%= check_employee_attendance_for_today(employee).status %></td>
<% else %>
  <td><%= "Absent" %></td>
<% end%>
<td>
  <% if check_employee_attendance_for_today(employee) != nil && check_employee_attendance_for_today(employee).status === "Present"%>
    <%= link_to "Mark Absent", mark_attendance_employee_path(employee, status: 'Absent'), remote: true, :class => 'btn btn-danger btn-xs', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))} %>
  <% else %>
    <%= link_to "Mark Present", mark_attendance_employee_path(employee, status: 'Present'), remote: true, :class => 'btn btn-success btn-xs' %>
  <% end %>
</td>

app/views/attendances/index.html.erb
<%- model_class = Attendance -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div class="table-responsive">
  <table class="table table-striped">
    <h3>Date :- <%= Date.current %></h3>
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:employee_name) %></th>
        <th><%= model_class.human_attribute_name(:status) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th> 
      </tr>
    </thead>
    <tbody>
      <% @employees.each do |employee| %>
        <tr id="<%= employee.id %>">
          <%= render "attendances/employee_details", employee: employee %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/employees/_form.html.erb
<%= form_for @employee, :html => { :class => "form-horizontal professor" } do |f| %>

  <%#= render "shared/error",object: @professor%>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :license_number, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :license_number, :class => 'form-control' %>
    </div>
    <%=f.error_span(:license_number) %>
  </div>
  
  <div class="form-group">
    <%= f.label :adhaar_number, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :adhaar_number, :class => 'form-control' %>
    </div>
    <%=f.error_span(:adhaar_number) %>
  </div>  

  <div class="form-group">
    <%= f.label :mobile_number, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :mobile_number, :class => 'form-control' %>
    </div>
    <%=f.error_span(:mobile_number) %>
  </div> 

  <div class="form-group">
    <%= f.label :salary, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :salary, :class => 'form-control' %>
    </div>
    <%=f.error_span(:salary) %>
  </div>

  <div class="form-group">
    <%= f.label :designation, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :designation, ['manger', 'driver', 'conductor'], { prompt: 'Select Designation' }, class: 'form-control' %>
    </div>
    <%=f.error_span(:designation) %>
  </div>
  
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                employees_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/employees/edit.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/employees/index.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <div class="pull-right">
    <%= link_to t('.new', :default => t("helpers.links.new")),
              new_employee_path,
              :class => 'btn btn-primary' %>
  </div>
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>

        <th><%= model_class.human_attribute_name(:name) %></th>
        <th><%= model_class.human_attribute_name(:license_number) %></th>
        <th><%= model_class.human_attribute_name(:adhaar_number) %></th>
        <th><%= model_class.human_attribute_name(:mobile_number) %></th>
        <th><%= model_class.human_attribute_name(:salary) %></th>
        <th><%= model_class.human_attribute_name(:designation) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th> 
      </tr>
    </thead>
    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= link_to employee.name.titleize, employee_path(employee) %></td>
          <td><%= employee.license_number %></td>
          <td><%= employee.adhaar_number %></td>
          <td><%= employee.mobile_number %></td>
          <td><%= employee.salary %></td>
          <td><%= employee.designation %></td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),edit_employee_path(employee), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        employee_path(employee),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>

          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/employees/mark_attendance.js.erb
$("#<%= @employee.id %>").html("<%= escape_javascript(render 'attendances/employee_details', employee: @employee) %>");

app/views/employees/new.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/employees/show.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @employee.name %></dd>

  <dt><strong><%= model_class.human_attribute_name(:license_number) %>:</strong></dt>
  <dd><%= @employee.license_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:adhaar_number) %>:</strong></dt>
  <dd><%= @employee.adhaar_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mobile_number) %>:</strong></dt>
  <dd><%= @employee.adhaar_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:designation) %>:</strong></dt>
  <dd><%= @employee.designation %></dd>
  <dt><strong><%= model_class.human_attribute_name(:is_working) %>:</strong></dt>
  <dd><%= @employee.is_working %></dd>

</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              employees_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_employee_path(@employee), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              employee_path(@employee),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoProduct</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
  <div class="navbar navbar-default navbar-static-top">
    <div class="container">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= render '/shared/header' %>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <%= bootstrap_flash %>
        <%= yield %>
        <div id="cover-spin"></div>
      </div>
    </div><!--/row-->

  </div> 

</body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li><%= link_to "Sites", sites_path %></li>
          <li><%= link_to "Employees", employees_path %></li>
          <li><%= link_to "Mark Attendance", attendances_path %></li>
          <li><%#= link_to "Trip Record", trip_records_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li>
            <%= drop_down "#{current_user.try(:email).try(:capitalize)} " do %>
              <%= menu_item "Log Out", destroy_user_session_path, method: :delete, class: "logout"%>
            <% end %>    
          </li>
        <% else %>
          <li><%= menu_group  do %>
            <%= menu_item "Log In", new_user_session_path %>
          <% end %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/sites/_form.html.erb
<%= form_for @site, :html => { :class => "form-horizontal professor" } do |f| %>

  <%#= render "shared/error",object: @professor%>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :default_truck_capacity, "Capacity(Cubic quantity)", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :default_truck_capacity, :class => 'form-control' %>
    </div>
    <%=f.error_span(:default_truck_capacity) %>
  </div>
  
  <div class="form-group">
    <%= f.label :lnt_basic_charge, "First KiloMeter Charge", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :lnt_basic_charge, :class => 'form-control' %>
    </div>
    <%=f.error_span(:lnt_basic_charge) %>
  </div>  

  <div class="form-group">
    <%= f.label :lnt_leading_charge, "More than 1 KiloMeter Charge", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :lnt_leading_charge, :class => 'form-control' %>
    </div>
    <%=f.error_span(:lnt_leading_charge) %>
  </div> 

  <div class="form-group">
    <%= f.label :excavation_charges, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :excavation_charges, :class => 'form-control' %>
    </div>
    <%=f.error_span(:excavation_charges) %>
  </div>
  
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                sites_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/sites/edit.html.erb
<%- model_class = Site -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sites/index.html.erb
<%- model_class = Site -%>
<div class="page-header">
  <div class="pull-right">
    <%= link_to t('.new', :default => t("helpers.links.new")),
              new_site_path,
              :class => 'btn btn-primary' %>
  </div>
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>

        <th><%= model_class.human_attribute_name(:name) %></th>
        <th><%= model_class.human_attribute_name(:capacity_cubic_quantity) %></th>
        <th><%= model_class.human_attribute_name(:first_kilometer_charge) %></th>
        <th><%= model_class.human_attribute_name(:more_than_1_km_charge) %></th>
        <th><%= model_class.human_attribute_name(:excavation_charges) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th> 
      </tr>
    </thead>
    <tbody>
      <% @sites.each do |site| %>
        <tr>
          <td><%= link_to site.name.titleize, site_path(site) %></td>
          <td><%= site.default_truck_capacity %></td>
          <td><%= site.lnt_basic_charge %></td>
          <td><%= site.lnt_leading_charge %></td>
          <td><%= site.excavation_charges %></td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),edit_site_path(site), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        site_path(site),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
            <%= link_to "Check Trip Records", site_trip_records_path(site_id: site), :class => 'btn btn-default btn-xs' %>

          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/sites/new.html.erb
<%- model_class = Site -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/trip_records/_form.html.erb
<%= form_for [@site, @trip_record], :html => { :class => "form-horizontal professor" } do |f| %>

  <%= f.hidden_field :site_id, :value => @site.id %>
  <%= f.hidden_field :site_truck_capacity, :value => @site.default_truck_capacity, :class => "truck-capacity"%>
  <div class="form-group">
    <%= f.label :date, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.date_field :trip_date, :class => 'form-control' %>
    </div>
    <%=f.error_span(:trip_date) %>
  </div>
  <div class="form-group">
    <%= f.label :trip_count, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :trip_count, :class => 'form-control' %>
    </div>
    <%=f.error_span(:trip_count) %>
  </div>
  
  <div class="form-group">
    <%= f.label :distance, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :distance, :class => 'form-control' %>
    </div>
    <%=f.error_span(:distance) %>
  </div>  

  <div class="form-group">
    <%= f.label :truck_capacity, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :truck_capacity, :class => 'form-control truck_capacity' %>
    </div>
    <%=f.error_span(:truck_capacity) %>
  </div>

  
  <div class="form-group">
    <%= f.label :diesel_quatity, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :diesel_quatity, :class => 'form-control' %>
    </div>
    <%=f.error_span(:diesel_quatity) %>
  </div> 

  <div class="form-group">
    <%= f.label :diesel_price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :diesel_price, :class => 'form-control' %>
    </div>
    <%=f.error_span(:diesel_price) %>
  </div>

  <div class="form-group">
    <%= f.label :chainage, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :chainage, :class => 'form-control' %>
    </div>
    <%=f.error_span(:chainage) %>
  </div>

  <div class="form-group">
    <%= f.label :excavation_done, :class => 'control-label col-lg-2' %>
    <div class="col-lg-4">
      <%= f.check_box :excavation_done, {class: 'mb-2 is_correct check_box'} %>
    </div>
    <%=f.error_span(:excavation_done) %>
    
    <%= f.label :loading_and_trasportaion_done, :class => 'control-label col-lg-2' %>
    <div class="col-lg-4">
      <%= f.check_box :loading_and_trasportaion_done, {class: 'mb-2 is_correct check_box'} %>
    </div>
    <%=f.error_span(:loading_and_trasportaion_done) %>
  </div>

  

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                site_trip_records_path(params[:site_id]), :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/trip_records/edit.html.erb
<%- model_class = TripRecord -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/trip_records/index.html.erb
<%- model_class = TripRecord -%>
<div class="page-header">
  <div class="pull-right">
    <%= link_to t('.new', :default => t("helpers.links.new")),
              new_site_trip_record_path(site_id: @site.id),
              :class => 'btn btn-primary' %>
  </div>
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>

        <th><%= model_class.human_attribute_name(:trip_date) %></th>
        <th><%= model_class.human_attribute_name(:trip_count) %></th>
        <th><%= model_class.human_attribute_name(:capacity_per_cubic) %></th>
        <th><%= model_class.human_attribute_name(:distance) %></th>
        <th><%= model_class.human_attribute_name(:revenue) %></th>
        <th><%= model_class.human_attribute_name(:diesel_quatity) %></th>
        <th><%= model_class.human_attribute_name(:diesel_price) %></th>
        <th><%= model_class.human_attribute_name(:total_diesel_price) %></th>
        <th><%= model_class.human_attribute_name(:amount_left) %></th>
        <th><%= model_class.human_attribute_name(:chainage) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th> 
      </tr>
    </thead>
    <tbody>
      <% @trip_records.each do |trip_record| %>
        <tr>

          <td><%= trip_record.trip_date %></td>
          <td><%= trip_record.trip_count %></td>
          <td><%= trip_record.truck_capacity %></td>
          <td><%= trip_record.distance %></td>
          <td><%= trip_record.revenue %></td>
          <td><%= trip_record.diesel_quatity %></td>
          <td><%= trip_record.diesel_price %></td>
          <td><%= calculate_diesel_price(trip_record.diesel_quatity, trip_record.diesel_price) %></td>
          <td><%= calculate_amount_left(trip_record.revenue, calculate_diesel_price(trip_record.diesel_quatity, trip_record.diesel_price)) %></td>
          <td><%= trip_record.chainage %></td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),edit_site_trip_record_path(trip_record.site, trip_record), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        site_trip_record_path(trip_record.site, trip_record),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>

          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/trip_records/new.html.erb
<%- model_class = TripRecord -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>